EXP_NAME: 'damon_hrnet_testing'
PROJECT_NAME: 'DECO_DAMON_Testing'
OUTPUT_DIR: 'deco_results'
CONDOR_DIR: ''
DATASET:
  BATCH_SIZE: 16
  NUM_WORKERS: 4
  NORMALIZE_IMAGES: [True]
OPTIMIZER:
  TYPE: 'adam'
  LR: [5e-5]
  NUM_UPDATE_LR: 3
TRAINING:
  ENCODER: 'hrnet'
  CONTEXT: [True]
  NUM_EPOCHS: 1
  NUM_EARLY_STOP: 10
  SUMMARY_STEPS: 5
  CHECKPOINT_EPOCHS: 5
  DATASETS: ['damon']
  DATASET_MIX_PDF: ['1.']
  DATASET_ROOT_PATH: ''
  BEST_MODEL_PATH: './checkpoints/Release_Checkpoint/deco_best.pth'
  PAL_LOSS_WEIGHTS: 0.0
VALIDATION:
  SUMMARY_STEPS: 1000
  DATASETS: ['damon']
  MAIN_DATASET: 'damon'